"""Example code for Software Systems at Olin College.

Copyright 2014 Allen Downey
License: Creative Commons Attribution-ShareAlike 3.0

"""

import glob
import sys

import matplotlib.pyplot as pyplot


def read_file(filename):
    """Reads a timing file and returns a list of (t, s) pairs.

    filename: string timing file generated by the instrumented version
              of wget

    t is a time in ms
    s is the total number of bytes presented to the application layer
    """
    res = []

    # add a fake packet at the beginning so the connect time is visible 
    lasts = 1460

    for line in open(filename):
        t, s = [float(x) for x in line.split()]
        res.append((t, lasts))
        res.append((t, s))
        lasts = s

    return res


def make_graph(dirname):
    """Makes a graph of the timing charts in the given directory.

    Graphs all files in the directory that match the pattern
    timing.[0-9]*.[0-9]*

    dirname: string
    """
    pattern = '%s/timing.[0-9]*.[0-9]*' % dirname
    filenames = glob.glob(pattern)

    data = []
    for filename in filenames:
        pairs = read_file(filename)
        data.append(pairs)

    for pairs in data:
        xs, ys = zip(*pairs)
        pyplot.plot(xs, ys, alpha=0.4, linewidth=1)

    pyplot.xlabel('time (ms)')
    pyplot.ylabel('bytes received')

    if dirname == '.':
        filename = 'timing.png'
    else:
        filename = 'timing.%s.png' % dirname

    print 'Writing', filename
    pyplot.savefig(filename, format='png', dpi=150)
    pyplot.show()


def main(script, dirname='.'):
    make_graph(dirname)

    
if __name__ == '__main__':
    main(*sys.argv)
